### ISSUE TITLE
Allow setting custom images for different modules

### ISSUE THREAD

**Issue by lbroudoux** [lbroudoux/apicurio-studio-operator#3]
As of today, operator will use hard references to container images to use. eg. `apicurio/apicurio-studio-ws:latest` for the WS module.

We should provide a way to override this and setup custom images for the different modules.

Proposed CR syntax:

```yaml
apiVersion: studio.apicur.io/v1alpha1
kind: ApicurioStudio
metadata:
  name: apicurio-sample
spec:
  name: apicurio-sample
  wsModule:
    image: quay.io/lbroudoux/apicurio-studio-ws:latest
```
